### ISSUE TITLE
제안: API 모듈 모듈명, 함수명, 변수명 정리

### ISSUE THREAD

**Issue by achimkoh** [Code-for-Korea/Industrial_disasters#1]
안녕하세요? @red112 님이 작성해주신 [API 크롤링 코드](https://github.com/Code-for-Korea/Industrial_disasters/blob/main/Extract_details_From_OpenData/API_Industrial_disasters.py) 잘 읽어보았습니다.

지금 있는 코드를 조금 정리하면 향후 작업을 진행할 때 편하겠다고 생각했습니다. 여기서 얘기하는 정리는 다음의 내용을 포함합니다.
- snake_case와 CamelCase가 혼용된 변수명, 함수명, 모듈명을 파이썬 컨벤션인 snake_case로 통일
- 가능할 경우 긴 변수명을 간결하게 변경
- result -> response 또는 res 등 컨벤션에 부합하는 변수명으로 수정
- 사건, 유형, 질병 등 중요 개념의 영문 변수명을 향후 구축할 DB 모델 상의 속성 영문명과 통일 (의사결정이 된 후)

API 코드를 다른 곳에서 재사용할 일이 꾸준히 생길 것으로 예상되므로, 위와 같은 수정을 해놓으면 코드 유지관리가 더 편할 것으로 생각합니다.

**Comment by red112** [comment]
좋은 의견 감사드려요~^^
저는 python을 시작한지 얼마 되지 않아서, 여러가지 관점에서 다듬을 부분들이 많을 것 같아요.
이 코드는 DB를 내려받는 목적으로 빨리 만들기 위해서 이것저것 많이 고려하지 않고 만들었어요. Server쪽 개발하시면서, Jinha님과도 말씀 나누며 정의하는 모델을 이 프로젝트의 표준으로 삼으면 좋을 것 같아요.
 변수명들의 표준화도 server의 model을 참고해서 제가 수정하도록 하겠습니다.
 그리고, API 코드를 여기서 계속 관리하기 보다는 server에 넣어두고 함께 관리하는 것도 좋을 것 같아요.

**Comment by red112** [comment]
1. result -> res
2. snake_case 적용 - pycharm에서 알려주는 PEP 8 warning들을 (API URL이 긴 것 빼고) 다 수정했습니다. 변수명도 가급적 간결하게 다시 줄였습니다.
3. DB 변수명으로 정의 된 명칭을 적용했습니다.
