### ISSUE TITLE
제안: API 크롤러 작동 로직 수정

### ISSUE THREAD

**Issue by achimkoh** [Code-for-Korea/Industrial_disasters#2]
API를 이용해 [산재보험 판례 판결문을 수집하는 코드](https://github.com/Code-for-Korea/Industrial_disasters/blob/main/Extract_details_From_OpenData/API_Industrial_disasters.py)에 대한 제안입니다.

판례 상세 내용 조회 API를 kindA, kindB, kindC 패러미터 없이 실행해보면 유형으로 필터링하지 않은 판례 목록이 그냥 나오는 것을 확인할 수 있습니다. 유형별 사건 개수 조회도 마찬가지로 필터링하지 않은 전체 사건 개수가 나옵니다. 따라서 판례 내용을 필터 없이 일괄 수집한 후 DB에 입력하는 것이 더 효율적일 수 있습니다. 지금 단계에서 큰 문제는 아니지만 주기적으로 사건을 다시 수집하고 DB를 업데이트하는 작업을 하게 될 때에는 개선이 도움이 될 것 같습니다.

**Comment by red112** [comment]
아~~~~ 그래요??? ㅋㅋ
API 문서 대충 보면서 후다닥 만들다보니 몰랐네요. 그걸 알았으면 훨씬 수월했을텐데 말이죠.
당장 pythonanywhere에 올려서 timeout 걸리는 것 해소에도 도움이 될 수 있겠네요.
제안 감사합니다.

**Comment by red112** [comment]
**말씀 해 주신 사항 반영해서 다시 수정 해 두었습니다. 좋은 제안 감사합니다.**
pythonanywhere에서는 timeout 시간 문제는 이것으로 해결이 되었는데, 대량 데이터를 받으면서 tmp 폴더를 많이 쓰나봅니다. 무료 제공 용량이 512메가라서 금방 차버려서 파일 쓰기가 안되더라구요. 그래서, Azure를 한번 살펴보고 있는데, 이것도 처음 접하니 복잡한게  많네요.
