### ISSUE TITLE
오류: 판결문 뒷쪽에 '주문'이 포함될 경우 연관판결 검색식 오작동

### ISSUE THREAD

**Issue by achimkoh** [Code-for-Korea/Industrial_disasters#3]
관련 코드: https://github.com/Code-for-Korea/Industrial_disasters/blob/main/Extract_details_From_OpenData/API_Industrial_disasters.py#L114-L127

문제: 연관판결 번호 직후가 아닌, 판결문 본문 중에 '주문' 문자열이 등장할 경우 해당 문자열까지의 모든 텍스트가 연관판결로 잡힙니다.

해결책: find 대신 정규식을 사용합니다: `r'(?:연관판결 \: )(.*)(?: ){3,}'`

코드 수정해서 PR 열도록 하겠습니다.

**Comment by red112** [comment]
처음 만들 때 데이터 전체를 다 검증하지는 못했었어요.^^
잘 짚어주셔서 감사합니다.

수정은 부담없이 편히 하셔도 됩니다.

**Comment by red112** [comment]
말씀 해 주신 사항 반영 해 두었습니다. 덕분에 많이 배웁니다.
좋은 말씀 감사드리고, server쪽의 일도 나눠서 할 부분들 말씀 해 주시면 감사하겠습니다.
주말동안 자잘한 잡일이라도 좀 해둘까 했는데 행여나 수정하시는데 방해 될까봐 server 코드는 엑셀파일 가져올 때 인코딩 처리만 수정했어요.(제 PC에서는 그렇게 해야 되더라구요. 괜히 건드렸나 싶기도 하고..ㅋㅋ)

django는 저 보다 경험이 많으시니 분담해야 할 만한 일들 나눠주시면 좋겠어요.

**Comment by achimkoh** [comment]
오 어느새 수정해주셨네요! 감사합니다!
